<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>syncfusion.documenteditor.wpf.app</AssemblyName>
    <RootNamespace>syncfusion.documenteditor.wpf.app</RootNamespace>
    <TargetFrameworkVersion>
    </TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0-windows' ">
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Controls.DisableDynamicResourceOptimization" Value="true" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFRAMEWORK' ">
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xaml">
      <RequiredTargetFramework>4.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="syncfusion.DocumentEditor.wpf_lib_Net462.csproj">
      <Name>syncfusion.DocumentEditor.wpf_lib</Name>
    </ProjectReference>
    <None Remove="Assets\documenteditor\*" />
    <Compile Remove="Converter\*" />
    <Compile Remove="Model\*" />
    <Compile Remove="ViewModel\*" />
    <Page Remove="Views\*" />
    <Compile Remove="Views\*" />
    <PackageReference Include="Syncfusion.Compression.Base" Version="34.1.29" />
    <PackageReference Include="Syncfusion.DocIO.Wpf" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SfBusyIndicator.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SfInput.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SfRichTextBoxAdv.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SfRichTextRibbon.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.MaterialLight.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.MaterialDark.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.MaterialLightBlue.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.MaterialDarkBlue.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.Office2019Black.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Themes.Office2019Colorful.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Licensing" Version="34.1.29" />
  </ItemGroup>
  <Import Project="..\..\targets\MultiTargeting_Net462.targets" />
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
</Project>